# Generated by Django 5.1.6 on 2025-02-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracoes', '__first__'),
        ('avaliacoes', '__first__'),
        ('comentarios', '__first__'),
        ('enderecos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pontos_turisticos')),
                ('atracoes', models.ManyToManyField(to='atracoes.atracao')),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentarios.comentario')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco')),
            ],
        ),
    ]
