# Generated by Django 5.1.4 on 2025-01-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enderecos.endereco",
            ),
        ),
    ]
