# Generated by Django 5.1.4 on 2025-01-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pontoturistico_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="pontos_turisticos"
            ),
        ),
    ]
