# Generated by Django 5.1.6 on 2025-02-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
