# Generated by Django 5.1.4 on 2025-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atracoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atracao",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="atracoes"),
        ),
    ]
